import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="h-screen w-full bg-sidebar p-3 flex gap-3 flex-col xl:flex-row overflow-hidden">
      <div className="flex-1 bg-background rounded-2xl border shadow-sm p-6">
        {children}
      </div>
      <div className="max-w-2xl hidden xl:flex items-end p-6 relative">
        <div className="w-1/2 aspect-square rounded-full translate-x-1/2 -translate-y-1/2 absolute top-0 right-0 border-100"></div>
        <div className="w-full space-y-3">
          <div className="px-3 py-1.5 border rounded-2xl bg-background text-xs md:text-base text-muted-foreground inline-flex items-center gap-3">
            <span className="w-3 h-3 rounded-full bg-primary"></span>
            Business email, without the bloat
          </div>
          <div className="space-y-1.5">
            <div className="text-2xl sm:text-3xl lg:text-4xl leading-normal text-foreground w-full font-bold">
              Your Marrow
              <span className="text-primary italic">mail</span> account
            </div>
            <div className="text-muted-foreground text-sm sm:text-base lg:text-lg w-full">
              Start onboarding, secure your domain, and build your mailbox
              structure from one place.
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
